function safeJson(value) {
  return JSON.stringify(value).replace(/</g, '\\u003c')
}

export function exportDesktopHtml(workspace, data) {
  const title = `${workspace.name} · OneBench`
  const payload = safeJson({ workspace, data })
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title>
<style>body{margin:0;min-width:320px;background:#141614;color:#f7f7f2;font:15px -apple-system,BlinkMacSystemFont,"Noto Sans SC",sans-serif}main{min-height:100vh;padding:44px clamp(20px,6vw,100px);box-sizing:border-box;background:#161916}h1{margin:0;font-size:clamp(26px,4vw,52px)}header{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:34px;color:#e7e9e1}header span{color:#aeb3aa;font-size:13px}.grid{display:grid;grid-template-columns:1.2fr .9fr .9fr;gap:14px;max-width:1100px}.card{min-height:150px;padding:18px;border:1px solid #3b403a;border-radius:16px;background:#20241f}.card h2{margin:0 0 14px;font-size:15px}.tasks{grid-row:span 2}.task{display:flex;gap:8px;padding:9px 0;border-bottom:1px solid #343a33}.task input{accent-color:#9bc17c}textarea,input{width:100%;box-sizing:border-box;border:0;border-radius:9px;background:#2b302a;color:#f7f7f2;padding:10px}textarea{min-height:115px;resize:vertical}.add{display:flex;gap:8px;margin-top:12px}button{border:0;border-radius:9px;background:#9bc17c;color:#152013;padding:9px 12px;font-weight:700;cursor:pointer}.modules{display:flex;flex-wrap:wrap;gap:8px}.modules span{padding:7px 9px;border-radius:999px;background:#2e352d;color:#d9dfd3;font-size:12px}.hint{color:#aeb3aa;font-size:12px;line-height:1.7}@media(max-width:720px){main{padding:26px 16px}.grid{grid-template-columns:1fr}.tasks{grid-row:auto}}</style></head>
<body><main><header><div><span>本地版 · 数据只在这台电脑</span><h1>${workspace.name}</h1></div><time id="clock"></time></header><section class="grid"><article class="card tasks"><h2>今天待办</h2><div id="tasks"></div><form class="add" id="add"><input id="new-task" placeholder="添加一件要做的事"><button>添加</button></form></article><article class="card"><h2>快速记录</h2><textarea id="note" placeholder="记下一点灵感、会议纪要或今天的复盘…"></textarea></article><article class="card"><h2>已装入模块</h2><div class="modules" id="modules"></div></article><article class="card"><h2>使用说明</h2><p class="hint">把此文件放到桌面，双击即可打开。需要手机和多台电脑同步时，请让智能体为你升级为私有仓库同步版。</p></article></section></main><script>const seed=${payload};const key='onebench-local-'+seed.workspace.id;let state=JSON.parse(localStorage.getItem(key)||'null')||seed.data;const $=s=>document.querySelector(s);function save(){localStorage.setItem(key,JSON.stringify(state))}function render(){ $('#tasks').innerHTML=state.tasks.map(t=>'<label class="task"><input type="checkbox" data-id="'+t.id+'" '+(t.done?'checked':'')+'><span>'+t.title.replace(/</g,'&lt;')+'</span></label>').join(''); $('#note').value=state.quickNote||'';$('#modules').innerHTML=seed.workspace.modules.map(m=>'<span>'+m.id+'</span>').join('')}render();$('#tasks').onchange=e=>{const id=e.target.dataset.id;state.tasks=state.tasks.map(t=>t.id===id?{...t,done:e.target.checked}:t);save()};$('#note').oninput=e=>{state.quickNote=e.target.value;save()};$('#add').onsubmit=e=>{e.preventDefault();const input=$('#new-task');if(!input.value.trim())return;state.tasks.push({id:crypto.randomUUID(),title:input.value.trim(),done:false});input.value='';save();render()};setInterval(()=>{$('#clock').textContent=new Date().toLocaleString('zh-CN',{hour:'2-digit',minute:'2-digit',weekday:'short'})},1000);</script></body></html>`
}
